---
- name: Add kibana repo
  yum_repository:
    name: kibana-{{ kibana_version }}
    description: Kibana repo
    baseurl: https://artifacts.elastic.co/packages/{{ kibana_version }}/yum
    enabled: yes
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
